### ISSUE TITLE
often "negative" vs. "non-positive"

### ISSUE THREAD

**Issue by Travis-S** [Travis-S/2016_MaxLik_Tomography#2]
From @dsuess:

> At the very top, the sentence "In this case, $\hat\rho$ is often negative” is not correct, but it’s clear from the context that you meant non-positive.

We can change that.

**Comment by DevChive** [comment]
I do not recall making this post. Are you sure you have the right person?

**Comment by Travis-S** [comment]
@dsuess I do have the wrong person. My mistake! I meant @dseuss.

**Comment by Travis-S** [comment]
Fixed by version 3 (at the latest).
